---
title: "climate_fever_data_sentiment_analysis"
output: html_document
date: "2023-06-15"
---

# ~~~~~~~~~~ PART ONE : All Claims Analysis ~~~~~~~~~~

# Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(syuzhet) # allows use of sentiment analysis functions
library(ggplot2) # allows use of ggplot functions
library(jsonlite) # allows us to read json files
library(dplyr) # allows use of pipe operator
library(tidyverse) # allows us to do lots of fundamental data science tasks (ex. read_csv)
library(tidytext) # fixes loading nrc chunk 
library(here) # allows us to cut out long file paths (ex. "users/connor/dowloads/etc")
```

# Load NRC lexicon
```{r}
nrc_lexicon <- get_sentiments("nrc")
head(nrc_lexicon)
```

# Import "climate-fever-dataset-r1.jsonl" file
```{r}
climate_fever_data <- stream_in(file("data/climate-fever-dataset-r1.jsonl"))
```

# Create vector from claims column
```{r}
all_claims_vector <- as.character(climate_fever_data$claim)
head(all_claims_vector)
```

# Run sentiment analysis function on all claims data
```{r}
all_claims_sentiment <- get_nrc_sentiment(all_claims_vector)
head(all_claims_sentiment)
```

# Sum sentiment analysis scores
```{r}
all_claims_sentiment_score <- data.frame(colSums(climate_fever_sentiment[,]))
head(all_claims_sentiment_score)
```

# Fix rows and columns for barplot
```{r}
# Viz Prep 1
names(all_claims_sentiment_score) <- 'score'
names(all_claims_sentiment_score)

# Viz Prep 2
all_claims_sentiment_score <- cbind("sentiment"=rownames(all_claims_sentiment_score), all_claims_sentiment_score)
names(all_claims_sentiment_score)

# Viz Prep 3
rownames(all_claims_sentiment_score) <- NULL

all_claims_sentiment_score
```

# Create first visual
```{r}
ggplot(data=all_claims_sentiment_score, aes(x=sentiment, y=score)) +
  geom_bar(aes(fill=sentiment), stat="identity") +
  theme(legend.position="none") +
  xlab("Sentiments") +
  ylab("Scores") +
  ggtitle("Sentiment Analysis on Climate Fever Data")
```

# Remove positive and negative sentiment from x axis
```{r}
all_claims_sentiment_score_edited <- climate_fever_sentiment_score[1:8,]
all_claims_sentiment_score_edited
```

# Rerun Visualization Code
```{r}

ggplot(data=climate_fever_sentiment_score_TWO, aes(x=sentiment, y=score))+
  geom_bar(aes(fill=sentiment), stat="identity") +
  theme(legend.position="none")+
  xlab("Sentiments")+
  ylab("Scores")+
  ggtitle("Sentiment Analysis on Climate Fever Data")
```

# ~~~~~~~~~~ PART TWO : Support, Refute, Dispute, NEI Analysis ~~~~~~~~~~

# 
```{r}

```

# 
```{r}

```

# 
```{r}

```

# 
```{r}

```

# 
```{r}

```

